[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
predicoid_1adaykeepsthedocteraway = "gE5vWTmKd3ehmYwwUk67UJNhSC8jfPyeiTBAkshf6uT"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
